FROM apache/airflow:2.5.1

# Install alpha-vintage or additional packages
RUN python -m pip install --upgrade pip

RUN pip install alpha_vantage==1.2.1
RUN pip install mysql-connector-python python-dotenv


